Update CI.yml

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -14,34 +14,34 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
   
-  build_backend:
-    runs-on: ubuntu-latest
-    needs: initialise
-    steps:
-      # Step 1: Checkout the code again in this job
-      - name: Checkout code
-        uses: actions/checkout@v3
+  # build_backend:
+  #   runs-on: ubuntu-latest
+  #   needs: initialise
+  #   steps:
+  #     # Step 1: Checkout the code again in this job
+  #     - name: Checkout code
+  #       uses: actions/checkout@v3
 
-      # Step 2: login dockerhub
-      - name: Login Dockerhub
-        env:
-          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
-          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
-        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
+  #     # Step 2: login dockerhub
+  #     - name: Login Dockerhub
+  #       env:
+  #         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
+  #         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+  #       run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
 
-      # Step 2: Build Docker image for Backend
-      - name: Build Backend Docker image
-        env:
-          ROCKET_DATABASES: ${{ secrets.ROCKET_DATABASES }}
-          ENV: ${{ secrets.ENV }}
-          XATA_API_KEY: ${{ secrets.XATA_API_KEY }}
-        run: |
-          cd striide-backend
-          docker build -t vineexoxo/striide-backend:latest .
+  #     # Step 2: Build Docker image for Backend
+  #     - name: Build Backend Docker image
+  #       env:
+  #         ROCKET_DATABASES: ${{ secrets.ROCKET_DATABASES }}
+  #         ENV: ${{ secrets.ENV }}
+  #         XATA_API_KEY: ${{ secrets.XATA_API_KEY }}
+  #       run: |
+  #         cd striide-backend
+  #         docker build -t vineexoxo/striide-backend:latest .
 
-      # Step 3: Push Docker image to Dockerhub
-      - name: Push striide-backend to Dockerhub
-        run: docker push vineexoxo/striide-backend:latest
+  #     # Step 3: Push Docker image to Dockerhub
+  #     - name: Push striide-backend to Dockerhub
+  #       run: docker push vineexoxo/striide-backend:latest
 
   build_frontend:
     runs-on: ubuntu-latest
@@ -72,18 +72,18 @@ jobs:
       - name: Push striide-frontend to Dockerhub
         run: docker push vineexoxo/striide-frontend:latest
 
-  remove_backend_image:
-    runs-on: ubuntu-latest
-    needs: build_backend
-    steps:
-      # Step 1: Checkout the code again in this job
-      - name: Checkout code
-        uses: actions/checkout@v3
+  # remove_backend_image:
+  #   runs-on: ubuntu-latest
+  #   needs: build_backend
+  #   steps:
+  #     # Step 1: Checkout the code again in this job
+  #     - name: Checkout code
+  #       uses: actions/checkout@v3
 
-      # Step 2: Clean up Backend Docker image
-      - name: Clean up Docker images
-        run: |
-          docker rmi vineexoxo/striide-backend:latest || true
+  #     # Step 2: Clean up Backend Docker image
+  #     - name: Clean up Docker images
+  #       run: |
+  #         docker rmi vineexoxo/striide-backend:latest || true
 
   remove_frontend_image:
     runs-on: ubuntu-latest
