checking

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -30,9 +30,10 @@ jobs:
       run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
   
   build_backend:
-      runs-on: ubuntu-latest
-      needs: initialise
+    runs-on: ubuntu-latest
+    needs: initialise
 
+    steps:
     # Step 3: Build Docker image for Backend
     - name: Build Backend Docker image
       env:
@@ -51,6 +52,7 @@ jobs:
     runs-on: ubuntu-latest
     needs: initialise
 
+    steps:
     # Step 5: Build Docker image for Frontend
     - name: Build Frontend Docker image
       env:
@@ -64,25 +66,30 @@ jobs:
       run: |
         cd striide-frontend
         docker build -t vineexoxo/striide-frontend:latest .
-
-  cleanup_images:
-    runs-on: ubuntu-latest
-    needs: build_frontend
-
-    # Step 6: Push Docker image to Dockerhub
+    #push docker image to docker hub
     - name: Push striide-frontend to Dockerhub
       run: docker push vineexoxo/striide-frontend:latest
 
-    # # Step 5: Run Docker Compose to bring up the containers
-    # - name: Run Docker Compose up
-    #   run: |
-    #     docker-compose -f docker-compose.yml up -d
+  remove_backend_image:
+    runs-on: ubuntu-latest
+    needs: build_frontend
 
-    # Step 7: Clean up Docker images
-    clean_images:
-    - name: Clean up Docker images
-      run: |
-        docker system prune -f
+    steps:
+      # Step 5: Clean up Docker images
+      - name: Clean up Docker images
+        run: |
+          docker rmi vineexoxo/striide-backend:latest || true
+
+  remove_frontend_image:
+    runs-on: ubuntu-latest
+    needs: remove_backend_image
+
+    steps:
+      # Step 8: Clean up Docker images
+      - name: Clean up Docker images
+        run: |
+          docker rmi vineexoxo/striide-frontend:latest || true
+
 
 # name: CI Pipeline
 
