my pc

diff --git a/.github/workflows/CICD.yml b/.github/workflows/CICD.yml
--- a/.github/workflows/CICD.yml
+++ b/.github/workflows/CICD.yml
@@ -46,36 +46,36 @@ jobs:
   #         docker rmi vineexoxo/striide-backend:latest || true
     
 
-  build_frontend:
-    runs-on: ubuntu-latest
-    needs: initialise
+  # build_frontend:
+  #   runs-on: ubuntu-latest
+  #   needs: initialise
 
-    steps:
-        #check code
-      - name: Checkout code
-        uses: actions/checkout@v3
+  #   steps:
+  #       #check code
+  #     - name: Checkout code
+  #       uses: actions/checkout@v3
 
-      #login dockerhub
-      - name: Login Dockerhub
-        env:
-          DOCKER_USERNAME: 'vineexoxo'
-          DOCKER_PASSWORD: 'Dockerina1'
-        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
+  #     #login dockerhub
+  #     - name: Login Dockerhub
+  #       env:
+  #         DOCKER_USERNAME: 'vineexoxo'
+  #         DOCKER_PASSWORD: 'Dockerina1'
+  #       run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
 
-      # Step 5: Build Frontend Docker image
-      - name: Build Frontend Docker image
-        run: |
-          cd striide-frontend
-          docker build -t vineexoxo/striide-frontend:latest .
+  #     # Step 5: Build Frontend Docker image
+  #     - name: Build Frontend Docker image
+  #       run: |
+  #         cd striide-frontend
+  #         docker build -t vineexoxo/striide-frontend:latest .
 
-      # Step 6: Push Frontend Docker image to Dockerhub
-      - name: Push striide-frontend to Dockerhub
-        run: docker push vineexoxo/striide-frontend:latest
+  #     # Step 6: Push Frontend Docker image to Dockerhub
+  #     - name: Push striide-frontend to Dockerhub
+  #       run: docker push vineexoxo/striide-frontend:latest
 
-      # Step 7: Clean up Backend Docker image
-      - name: Clean up Docker images
-        run: |
-          docker rmi vineexoxo/striide-frontend:latest || true
+  #     # Step 7: Clean up Backend Docker image
+  #     - name: Clean up Docker images
+  #       run: |
+  #         docker rmi vineexoxo/striide-frontend:latest || true
 
   # build_logserver:
   #   runs-on: ubuntu-latest
