this branch is for local deployment

diff --git a/.github/workflows/CICD.yml b/.github/workflows/CICD.yml
--- a/.github/workflows/CICD.yml
+++ b/.github/workflows/CICD.yml
@@ -1,14 +1,54 @@
-name: CD Pipeline
+name: CI Pipeline
 
-# Trigger only when the build flow is successful
 on:
-  workflow_run:
-    workflows: ["CI Pipeline"]
-    types:
-      - completed
+  push:
+    branches:
+      - main # Trigger on push to main branch
 
 jobs:
+  build_and_push:
+    runs-on: ubuntu-latest
+
+    steps:
+      # Step 1: Checkout the code from GitHub
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      # Step 2: Login to Dockerhub
+      - name: Login Dockerhub
+        env:
+          DOCKER_USERNAME: 'vineexoxo'
+          DOCKER_PASSWORD: 'Dockerina1'
+        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
+
+      # Step 3: Build Backend Docker image
+      - name: Build Backend Docker image
+        run: |
+          cd striide-backend
+          docker build -t vineexoxo/striide-backend:latest .
+
+      # Step 4: Push Backend Docker image to Dockerhub
+      - name: Push striide-backend to Dockerhub
+        run: docker push vineexoxo/striide-backend:latest
+
+      # Step 5: Build Frontend Docker image
+      - name: Build Frontend Docker image
+        run: |
+          cd striide-frontend
+          docker build -t vineexoxo/striide-frontend:latest .
+
+      # Step 6: Push Frontend Docker image to Dockerhub
+      - name: Push striide-frontend to Dockerhub
+        run: docker push vineexoxo/striide-frontend:latest
+
+      # Step 7: Clean up Docker images
+      - name: Clean up Docker images
+        run: |
+          docker rmi vineexoxo/striide-backend:latest || true
+          docker rmi vineexoxo/striide-frontend:latest || true
+
   deploy_backend:
+    needs: build_and_push
     runs-on: ubuntu-latest
 
     steps:
@@ -74,13 +114,3 @@ jobs:
       # Step 4: Clean up Docker images 
       - name: Clean up Docker images
         run: sudo docker image prune -f
-
-
-          # sudo docker run -d \
-          #   --name striide-backend-container \
-          #   -p 8000:8080 \
-          #   -e ROCKET_DATABASES=$ROCKET_DATABASES \
-          #   -e ENV=$ENV \
-          #   -e XATA_API_KEY=$XATA_API_KEY \
-          #dummy
-          #   vineexoxo/striide-backend:latest
