updated pipeline

diff --git a/.github/workflows/CICD.yml b/.github/workflows/CICD.yml
--- a/.github/workflows/CICD.yml
+++ b/.github/workflows/CICD.yml
@@ -6,14 +6,14 @@ on:
       - main # Trigger on push to main branch
 
 jobs:
-  build_and_push:
+  initialise:
     runs-on: ubuntu-latest
 
     steps:
-      # Step 1: Checkout the code from GitHub
+      # Step 1: Checkout code
       - name: Checkout code
         uses: actions/checkout@v3
-
+        
       # Step 2: Login to Dockerhub
       - name: Login Dockerhub
         env:
@@ -21,6 +21,11 @@ jobs:
           DOCKER_PASSWORD: 'Dockerina1'
         run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
 
+  build_backend:
+    runs-on: ubuntu-latest
+    needs: initialise
+
+    steps:
       # Step 3: Build Backend Docker image
       - name: Build Backend Docker image
         run: |
@@ -28,40 +33,59 @@ jobs:
           docker build -t vineexoxo/striide-backend:latest .
 
       # Step 4: Push Backend Docker image to Dockerhub
-      - name: Push striide-backend to Dockerhub
+      - name: Push Backend to Dockerhub
         run: docker push vineexoxo/striide-backend:latest
 
-      # Step 5: Build Frontend Docker image
+  remove_backend_image:
+    runs-on: ubuntu-latest
+    needs: build_backend
+
+    steps:
+      # Step 5: Clean up Docker images
+      - name: Clean up Docker images
+        run: |
+          docker rmi vineexoxo/striide-backend:latest || true
+
+  build_frontend:
+    runs-on: ubuntu-latest
+    needs: initialise
+
+    steps:
+      # Step 6: Build Frontend Docker image
       - name: Build Frontend Docker image
         run: |
           cd striide-frontend
           docker build -t vineexoxo/striide-frontend:latest .
 
-      # Step 6: Push Frontend Docker image to Dockerhub
-      - name: Push striide-frontend to Dockerhub
+      # Step 7: Push Frontend Docker image to Dockerhub
+      - name: Push Frontend to Dockerhub
         run: docker push vineexoxo/striide-frontend:latest
 
-      # Step 7: Clean up Docker images
+  remove_frontend_image:
+    runs-on: ubuntu-latest
+    needs: build_frontend
+
+    steps:
+      # Step 8: Clean up Docker images
       - name: Clean up Docker images
         run: |
-          docker rmi vineexoxo/striide-backend:latest || true
           docker rmi vineexoxo/striide-frontend:latest || true
 
   deploy_backend:
-    needs: build_and_push
     runs-on: ubuntu-latest
+    needs: build_backend
 
     steps:
-      # Step 1: Pull Backend Docker Image
-      - name: Pull Backend Docker Image
+      # Step 9: Pull Backend Docker image
+      - name: Pull Backend Docker image
         run: sudo docker pull vineexoxo/striide-backend:latest
 
-      # Step 2: Delete old Backend Docker Container (if exists)
-      - name: Delete old Backend Docker Container
+      # Step 10: Delete old Backend Docker container (if exists)
+      - name: Delete old Backend Docker container
         run: sudo docker rm -f striide-backend-container || true
 
-      # Step 3: Run Backend Docker Container
-      - name: Run Backend Docker Container
+      # Step 11: Run Backend Docker container
+      - name: Run Backend Docker container
         env:
           ROCKET_DATABASES: ${{ secrets.ROCKET_DATABASES }}
           ENV: ${{ secrets.ENV }}
@@ -75,31 +99,31 @@ jobs:
             -e XATA_API_KEY='xau_1d9LHuNg9qIh0dpuA14x1URryIQ5soOr3' \
             vineexoxo/striide-backend:latest
 
-      # Step 4: Clean up Docker images (optional)
+      # Step 12: Clean up Docker images (optional)
       - name: Clean up Docker images
         run: sudo docker image prune -f
 
   deploy_frontend:
-    needs: deploy_backend
     runs-on: ubuntu-latest
+    needs: deploy_backend
 
     steps:
-      # Step 1: Pull Frontend Docker Image
-      - name: Pull Frontend Docker Image
+      # Step 13: Pull Frontend Docker image
+      - name: Pull Frontend Docker image
         run: sudo docker pull vineexoxo/striide-frontend:latest
 
-      # Step 2: Delete old Frontend Docker Container (if exists)
-      - name: Delete old Frontend Docker Container
+      # Step 14: Delete old Frontend Docker container (if exists)
+      - name: Delete old Frontend Docker container
         run: sudo docker rm -f striide-frontend-container || true
 
-      # Step 3: Run Frontend Docker Container
-      - name: Run frontend Docker container
+      # Step 15: Run Frontend Docker container
+      - name: Run Frontend Docker container
         env:
-          NEXT_PUBLIC_MAPBOX_TOKEN: 'pk.eyJ1Ijoic3RyaWlkZSIsImEiOiJjbTQxaXh2ZmoyYzlwMmpxeno5YXR6cmxvIn0.pk3E4tHYcOWCNhuhwzNAiA'
-          NEXT_PUBLIC_MAPBOX_MAP_STYLE: 'mapbox://styles/striide/clyorf2ms024e01p81gy3577s'
-          NEXT_PUBLIC_API_URL: 'https://striide-45qob5kdnq-ue.a.run.app'
-          NEXT_PUBLIC_SEARCH_API_SESSION_TOKEN: '56fb4ac0-34e4-46df-b6a9-a6c86eb68ec3'
-          NEXT_PUBLIC_BACKEND_URL: 'http://127.0.0.1:8000'
+          NEXT_PUBLIC_MAPBOX_TOKEN: ${{ secrets.NEXT_PUBLIC_MAPBOX_TOKEN }}
+          NEXT_PUBLIC_MAPBOX_MAP_STYLE: ${{ secrets.NEXT_PUBLIC_MAPBOX_MAP_STYLE }}
+          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
+          NEXT_PUBLIC_SEARCH_API_SESSION_TOKEN: ${{ secrets.NEXT_PUBLIC_SEARCH_API_SESSION_TOKEN }}
+          NEXT_PUBLIC_BACKEND_URL: ${{ secrets.NEXT_PUBLIC_BACKEND_URL }}
         run: |
           sudo docker run -d \
             --name striide-frontend-container \
@@ -111,6 +135,7 @@ jobs:
             -p 3000:3000 \
             vineexoxo/striide-frontend:latest
 
-      # Step 4: Clean up Docker images 
+      # Step 16: Clean up Docker images
       - name: Clean up Docker images
-        run: sudo docker image prune -f
+        run: |
+          docker rmi vineexoxo/striide-frontend:latest || true
